export const studentRecord = {
  name: "Aarav Sharma",
  id: "STU2025CS001",
  programme: "B.Tech Computer Science",
  institution: "National Institute of Technology (Demo)",
  year: "Final Year",
  documents: [
    {
      id: 1,
      name: "10th Marksheet.pdf",
      type: "Marks Card",
      status: "Verified",
      lastChecked: "2025-11-01 09:45",
      integrityScore: 98,
    },
    {
      id: 2,
      name: "12th Marksheet.pdf",
      type: "Marks Card",
      status: "Verified",
      lastChecked: "2025-11-01 09:47",
      integrityScore: 96,
    },
    {
      id: 3,
      name: "B.Tech Provisional Degree.pdf",
      type: "Degree Certificate",
      status: "Pending",
      lastChecked: "—",
      integrityScore: 0,
    },
    {
      id: 4,
      name: "Previous University Degree.pdf",
      type: "Degree Certificate",
      status: "Flagged as Fake",
      lastChecked: "2025-11-01 09:50",
      integrityScore: 12,
    },
  ],
  semesters: [
    { sem: "Sem 1", sgpa: 8.2 },
    { sem: "Sem 2", sgpa: 8.5 },
    { sem: "Sem 3", sgpa: 8.7 },
    { sem: "Sem 4", sgpa: 8.9 },
    { sem: "Sem 5", sgpa: 9.0 },
    { sem: "Sem 6", sgpa: 8.8 },
  ],
};

export const centreSummary = {
  centreId: "CEN-MH-23",
  name: "Pune Central Exam Hub (Demo)",
  totalStudents: 480,
  present: 452,
  absent: 28,
  fraudIncidents: 5,
  securityScore: 92,
};

export const centreBiometricList = [
  {
    id: "STU2025CS001",
    name: "Aarav Sharma",
    room: "H-201",
    thumb: "MATCH",
    face: "MATCH",
    status: "Verified",
    time: "09:02",
  },
  {
    id: "STU2025ME014",
    name: "Pragya Nair",
    room: "H-202",
    thumb: "MATCH",
    face: "MISMATCH",
    status: "Manual Review",
    time: "09:05",
  },
  {
    id: "STU2025EE021",
    name: "Aditya Patel",
    room: "H-204",
    thumb: "MISMATCH",
    face: "MATCH",
    status: "Denied",
    time: "09:09",
  },
];

export const fraudSuspects = [
  {
    id: "STU2025ME014",
    name: "Pragya Nair",
    reason: "Photo on admit card differs from live capture",
    severity: "Medium",
  },
  {
    id: "STU2025EE021",
    name: "Aditya Patel",
    reason: "Duplicate biometric used at another centre",
    severity: "High",
  },
];

export const securityFraudList = [
  {
    id: "STU2025EE021",
    name: "Aditya Patel",
    hall: "H-204",
    alert: "Impersonation suspected",
    source: "Face & Thumb mismatch",
    timestamp: "09:12:23",
    riskScore: 92,
  },
  {
    id: "STU2025CV032",
    name: "Ritika Singh",
    hall: "H-105",
    alert: "Suspicious collaboration",
    source: "Camera 05 - Unusual body language",
    timestamp: "09:16:51",
    riskScore: 78,
  },
];

export const biometricAlerts = [
  {
    id: 1,
    type: "Thumb mismatch",
    userId: "STU2025EE021",
    hall: "H-204",
    severity: "High",
    time: "09:10",
  },
  {
    id: 2,
    type: "Face mismatch",
    userId: "STU2025ME014",
    hall: "H-202",
    severity: "Medium",
    time: "09:06",
  },
  {
    id: 3,
    type: "Signature mismatch",
    userId: "STU2025CV032",
    hall: "H-105",
    severity: "Low",
    time: "09:03",
  },
];

export const cameraFeeds = [
  { id: "CAM-01", hall: "H-101", status: "Online" },
  { id: "CAM-02", hall: "H-102", status: "Online" },
  { id: "CAM-03", hall: "H-201", status: "Degraded" },
  { id: "CAM-04", hall: "H-202", status: "Online" },
  { id: "CAM-05", hall: "H-105", status: "Online" },
  { id: "CAM-06", hall: "Corridor 3", status: "Offline" },
];

export const frequencyDevices = [
  { id: "FD-01", location: "H-101", status: "Active" },
  { id: "FD-02", location: "H-201", status: "Active" },
  { id: "FD-03", location: "H-204", status: "Active" },
  { id: "FD-04", location: "Corridor 3", status: "Inactive" },
];

export const accessLogs = [
  {
    id: 1,
    actor: "SEC007",
    role: "Security",
    action: "Viewed live camera feeds",
    status: "Allowed",
    time: "09:01:10",
    ip: "10.12.4.21",
  },
  {
    id: 2,
    actor: "ADM999",
    role: "Higher Authority",
    action: "Exported fraud analytics",
    status: "Allowed",
    time: "08:59:45",
    ip: "10.10.1.9",
  },
  {
    id: 3,
    actor: "CEN001",
    role: "Centre Staff",
    action: "Attempted to alter attendance",
    status: "Blocked",
    time: "08:55:12",
    ip: "10.11.3.5",
  },
];

export const authorityOverview = {
  activeExams: 126,
  centresOnline: 309,
  totalCandidates: 43820,
  flaggedCandidates: 213,
  authenticPercentage: 94,
  fakePercentage: 3,
  pendingPercentage: 3,
};

export const fraudCases = [
  {
    id: 1,
    entityType: "Student",
    refId: "STU2025EE021",
    name: "Aditya Patel",
    centre: "Pune Central",
    stateCode: "MH",
    issue: "Biometric impersonation",
    status: "Escalated",
  },
  {
    id: 2,
    entityType: "Staff",
    refId: "CEN-MH-23-OPS01",
    name: "Centre Operator 1",
    centre: "Pune Central",
    stateCode: "MH",
    issue: "Unauthorized attendance modification",
    status: "Under Review",
  },
];

export const analyticsSeries = {
  fraudTrend: [
    { month: "Jun", fraud: 32, attempted: 58 },
    { month: "Jul", fraud: 27, attempted: 49 },
    { month: "Aug", fraud: 18, attempted: 37 },
    { month: "Sep", fraud: 21, attempted: 40 },
    { month: "Oct", fraud: 15, attempted: 35 },
    { month: "Nov", fraud: 9, attempted: 24 },
  ],
  verificationRates: [
    { day: "Mon", verified: 92, pending: 5 },
    { day: "Tue", verified: 94, pending: 4 },
    { day: "Wed", verified: 90, pending: 7 },
    { day: "Thu", verified: 95, pending: 3 },
    { day: "Fri", verified: 93, pending: 4 },
  ],
  securityScoreDist: [
    { label: "High", value: 68 },
    { label: "Medium", value: 24 },
    { label: "Low", value: 8 },
  ],
};

// State-wise Fraud Data for India Heat Map
export const stateWiseFraudData = {
  "Andhra Pradesh": {
    state_code: "AP",
    fraud_density: 0.45,
    students: 12400,
    fraud_cases: 54,
    verification_rate: 92,
    risk_level: "critical",
  },
  "Arunachal Pradesh": {
    state_code: "AR",
    fraud_density: 0.12,
    students: 2100,
    fraud_cases: 8,
    verification_rate: 96,
    risk_level: "low",
  },
  "Assam": {
    state_code: "AS",
    fraud_density: 0.28,
    students: 8900,
    fraud_cases: 31,
    verification_rate: 94,
    risk_level: "medium",
  },
  "Bihar": {
    state_code: "BR",
    fraud_density: 0.38,
    students: 11200,
    fraud_cases: 42,
    verification_rate: 91,
    risk_level: "critical",
  },
  "Chhattisgarh": {
    state_code: "CG",
    fraud_density: 0.22,
    students: 6800,
    fraud_cases: 18,
    verification_rate: 95,
    risk_level: "low",
  },
  "Goa": {
    state_code: "GA",
    fraud_density: 0.08,
    students: 1200,
    fraud_cases: 3,
    verification_rate: 98,
    risk_level: "low",
  },
  "Gujarat": {
    state_code: "GJ",
    fraud_density: 0.25,
    students: 15600,
    fraud_cases: 39,
    verification_rate: 94,
    risk_level: "medium",
  },
  "Haryana": {
    state_code: "HR",
    fraud_density: 0.18,
    students: 7800,
    fraud_cases: 18,
    verification_rate: 96,
    risk_level: "low",
  },
  "Himachal Pradesh": {
    state_code: "HP",
    fraud_density: 0.10,
    students: 3200,
    fraud_cases: 5,
    verification_rate: 97,
    risk_level: "low",
  },
  "Jharkhand": {
    state_code: "JH",
    fraud_density: 0.35,
    students: 9400,
    fraud_cases: 35,
    verification_rate: 92,
    risk_level: "high",
  },
  "Karnataka": {
    state_code: "KA",
    fraud_density: 0.20,
    students: 14200,
    fraud_cases: 28,
    verification_rate: 95,
    risk_level: "low",
  },
  "Kerala": {
    state_code: "KL",
    fraud_density: 0.12,
    students: 8900,
    fraud_cases: 11,
    verification_rate: 97,
    risk_level: "low",
  },
  "Madhya Pradesh": {
    state_code: "MP",
    fraud_density: 0.32,
    students: 10800,
    fraud_cases: 38,
    verification_rate: 93,
    risk_level: "high",
  },
  "Maharashtra": {
    state_code: "MH",
    fraud_density: 0.28,
    students: 18900,
    fraud_cases: 56,
    verification_rate: 93,
    risk_level: "medium",
  },
  "Manipur": {
    state_code: "MN",
    fraud_density: 0.15,
    students: 1800,
    fraud_cases: 4,
    verification_rate: 96,
    risk_level: "low",
  },
  "Meghalaya": {
    state_code: "ML",
    fraud_density: 0.14,
    students: 2300,
    fraud_cases: 5,
    verification_rate: 96,
    risk_level: "low",
  },
  "Mizoram": {
    state_code: "MZ",
    fraud_density: 0.09,
    students: 1100,
    fraud_cases: 2,
    verification_rate: 98,
    risk_level: "low",
  },
  "Nagaland": {
    state_code: "NL",
    fraud_density: 0.11,
    students: 1400,
    fraud_cases: 3,
    verification_rate: 97,
    risk_level: "low",
  },
  "Odisha": {
    state_code: "OR",
    fraud_density: 0.24,
    students: 7600,
    fraud_cases: 22,
    verification_rate: 94,
    risk_level: "medium",
  },
  "Punjab": {
    state_code: "PB",
    fraud_density: 0.19,
    students: 6400,
    fraud_cases: 15,
    verification_rate: 95,
    risk_level: "low",
  },
  "Rajasthan": {
    state_code: "RJ",
    fraud_density: 0.31,
    students: 9800,
    fraud_cases: 32,
    verification_rate: 93,
    risk_level: "high",
  },
  "Sikkim": {
    state_code: "SK",
    fraud_density: 0.07,
    students: 800,
    fraud_cases: 1,
    verification_rate: 99,
    risk_level: "low",
  },
  "Tamil Nadu": {
    state_code: "TN",
    fraud_density: 0.22,
    students: 16200,
    fraud_cases: 35,
    verification_rate: 94,
    risk_level: "medium",
  },
  "Telangana": {
    state_code: "TG",
    fraud_density: 0.42,
    students: 11600,
    fraud_cases: 52,
    verification_rate: 91,
    risk_level: "critical",
  },
  "Tripura": {
    state_code: "TR",
    fraud_density: 0.13,
    students: 1900,
    fraud_cases: 4,
    verification_rate: 96,
    risk_level: "low",
  },
  "Uttar Pradesh": {
    state_code: "UP",
    fraud_density: 0.48,
    students: 22300,
    fraud_cases: 98,
    verification_rate: 90,
    risk_level: "critical",
  },
  "Uttarakhand": {
    state_code: "UT",
    fraud_density: 0.16,
    students: 4200,
    fraud_cases: 9,
    verification_rate: 95,
    risk_level: "low",
  },
  "West Bengal": {
    state_code: "WB",
    fraud_density: 0.34,
    students: 12800,
    fraud_cases: 47,
    verification_rate: 92,
    risk_level: "high",
  },
  // Union Territories
  "Andaman and Nicobar Islands": {
    state_code: "AN",
    fraud_density: 0.06,
    students: 320,
    fraud_cases: 1,
    verification_rate: 99,
    risk_level: "low",
  },
  "Chandigarh": {
    state_code: "CH",
    fraud_density: 0.10,
    students: 1800,
    fraud_cases: 3,
    verification_rate: 97,
    risk_level: "low",
  },
  "Dadra and Nagar Haveli": {
    state_code: "DN",
    fraud_density: 0.08,
    students: 600,
    fraud_cases: 1,
    verification_rate: 98,
    risk_level: "low",
  },
  "Daman and Diu": {
    state_code: "DD",
    fraud_density: 0.07,
    students: 400,
    fraud_cases: 1,
    verification_rate: 99,
    risk_level: "low",
  },
  "Delhi": {
    state_code: "DL",
    fraud_density: 0.26,
    students: 8900,
    fraud_cases: 24,
    verification_rate: 94,
    risk_level: "medium",
  },
  "Jammu and Kashmir": {
    state_code: "JK",
    fraud_density: 0.29,
    students: 5200,
    fraud_cases: 18,
    verification_rate: 93,
    risk_level: "medium",
  },
  "Ladakh": {
    state_code: "LA",
    fraud_density: 0.05,
    students: 280,
    fraud_cases: 0,
    verification_rate: 100,
    risk_level: "low",
  },
  "Puducherry": {
    state_code: "PY",
    fraud_density: 0.11,
    students: 2400,
    fraud_cases: 4,
    verification_rate: 97,
    risk_level: "low",
  },
};
